---
kick_cfg: ks.cfg
tftp_dir: /var/lib/tftpboot
web_root: /var/www/html
tfplenumoffline_dir: "{{ web_root }}/offlinerepo"
install_dir: /opt/tfplenum
tfplenum_vars: "{{ install_dir }}/playbooks/group_vars/all/versions.yml"

rhel_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms

additional_repo_info:
  kube:
    name: "kubernetes"
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    gpgkeyurl: "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
    gpgkeyname: "yum-key.gpg"
    description: "kubernetes repo"
    # Required because kube public repo uses relative path so this is a hack to fix it
    download_path: "{{ tfplenumoffline_dir }}/tmp"
  ceph_base:
    name: "ceph_base"
    baseurl: "https://download.ceph.com/rpm-luminous/el7/$basearch"
    gpgkeyurl: "https://download.ceph.com/keys/release.asc"
    gpgkeyname: "release.asc"
    description: "ceph base repo"
    download_path: "{{ tfplenumoffline_dir }}"
  ceph_noarch:
    name: "ceph_noarch"
    baseurl: "https://download.ceph.com/rpm-luminous/el7/$basearch"
    gpgkeyurl: "https://download.ceph.com/keys/release.asc"
    gpgkeyname: "release.asc"
    description: "ceph base repo"
    download_path: "{{ tfplenumoffline_dir }}"
  ceph_srpms:
    name: "ceph_srpms"
    baseurl: "https://download.ceph.com/rpm-luminous/el7/SRPMS"
    gpgkeyurl: "https://download.ceph.com/keys/release.asc"
    gpgkeyname: "release.asc"
    description: "ceph srpms repo"
    download_path: "{{ tfplenumoffline_dir }}"
  mongo:
    name: "mongodb-org-4.0"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/"
    gpgkeyurl: "https://www.mongodb.org/static/pgp/server-4.0.asc"
    gpgkeyname: "server-4.0.asc"
    description: "MongoDB Repository"
    download_path: "{{ tfplenumoffline_dir }}"
  docker_ce:
    name: "docker-ce"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
    gpgkeyurl: "https://download.docker.com/linux/centos/gpg"
    gpgkeyname: "gpg"
    description: "Docker CE repo"
    download_path: "{{ tfplenumoffline_dir }}"
  ansible:
    name: "ansible"
    baseurl: "https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/"
    gpgkeyurl: "https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub"
    gpgkeyname: "RPM-GPG-KEY-ansible-release.pub"
    description: "Ansible Repo"
    download_path: "{{ tfplenumoffline_dir }}"
    
epel_repo:
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
    gpgkeyurl: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    gpgkey:  "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"
    gpgcheck: true
    name: "epel"
    description: "epel repo"
    failovermethod: "priority"
    download_path: "{{ tfplenumoffline_dir }}"

labrepo_gpg_keys:
  epel:
    name: "epel"
    gpgkeyurl: "http://yum.labrepo.lan/epel/RPM-GPG-KEY-EPEL-7"
    gpgkeyname:  "RPM-GPG-KEY-EPEL-7"
  kube:
    name: "kubernetes"
    gpgkeyurl: "http://yum.labrepo.lan/kubernetes/yum-key.gpg"
    gpgkeyname: "yum-key.gpg"
  ceph_base:
    name: "ceph_base"
    gpgkeyurl: "http://yum.labrepo.lan/ceph_base/release.asc"
    gpgkeyname: "release.asc"
  ceph_noarch:
    name: "ceph_noarch"
    gpgkeyurl: "http://yum.labrepo.lan/ceph_noarch/release.asc"
    gpgkeyname: "release.asc"
  ceph_srpms:
    name: "ceph_srpms"
    gpgkeyurl: "http://yum.labrepo.lan/ceph_srpms/release.asc"
    gpgkeyname: "release.asc"
  mongo:
    name: "mongodb-org-4.0"
    gpgkeyurl: "http://yum.labrepo.lan/mongodb-org-4.0/server-4.0.asc"
    gpgkeyname: "server-4.0.asc"

bootstrap_package_names:
  - yum-utils
  - createrepo
  - bash-completion

gpg_keys:
  - "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  - "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
  - "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
  - "https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub"

pip_downloads:
  - docker-py
  - ipaddress
  - flask
  - requests
  - urllib3
  - junit-xml
  - elasticsearch
  - restresponse
  - kafka

iso_centos_version: 1810
iso_centos_url_online: "http://mirrors.mit.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-{{ iso_centos_version }}.iso"
iso_centos_url_labrepo: "http://isos.labrepo.lan/CentOS-7-x86_64-Minimal-{{ iso_centos_version }}.iso"
iso_centos_pth: "/root/CentOS-7-x86_64-Minimal-{{ iso_centos_version }}.iso"
iso_centos_checksum: 38d5d51d9d100fd73df031ffd6bd8b1297ce24660dc8c13a3b8b4534a4bd291c

iso_rhel_version: "7.5"
iso_rhel_pth: "/root/rhel-server-{{ iso_rhel_version }}-x86_64-dvd.iso"
iso_rhel_url_labrepo: "http://isos.labrepo.lan/rhel-server-{{ iso_rhel_version }}-x86_64-dvd.iso"
iso_rhel_checksum: d0dd6ae5e001fb050dafefdfd871e7e648b147fb2d35f0e106e0b34a0163e8f5

BOOTSTRAP: false

ansible_controller_hostname: "controller.lan"

RHEL_SOURCE_REPO: "{{ lookup('env','RHEL_SOURCE_REPO') | default('') }}"
TFPLENUM_OS_TYPE: "{{ lookup('env','TFPLENUM_OS_TYPE') | default('') }}"
BOOTSTRAP_VARS: "{{ web_root }}/bootstrap.yml"
TFPLENUM_REPO_DIR: "{{ tfplenumoffline_dir }}/tfplenum"

...
